# frozen_string_literal: true

source "https://rubygems.org"

gem "faraday", "~> 0.16.1"
gem "opentelemetry-api"
gem "opentelemetry-sdk"
gem "opentelemetry-exporter-otlp"
gem 'opentelemetry-instrumentation-all'
gem "sinatra", "~> 2.0"
